<a href="https://colab.research.google.com/github/harishmuh/Python-for-Data-Science-Analysis/blob/main/Introduction_to_Regex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Regex**

A regular expression (shortened to regex or regexp) is a sequence of characters that defines a search pattern. Such patterns are commonly used by string search algorithms to perform "search" or "search and replace" operations on strings, or to check input strings. Regular expressions are a technique developed in the fields of theoretical computer science and formal language theory.

The concept emerged in the 1950s when American mathematician Stephen Cole Kleene formalized the description of a regular language. Regular expressions are used to match or search for patterns in text such as in search engines, in search and replace dialogs in word processors and text editors, in text processing utilities and in lexical analysis. Most programming languages ​​provide regular expression processors either built-in or through libraries.

___

In [1]:
# Installing Regex
# !pip install regex

In [2]:
# Importing regex
import re

## **1. Searching for Patterns in Text**

One of the most common uses of the re module is to find patterns in text. Let's do a quick example of using the search method in the re module to find some text:

In [3]:
# List of patterns to search for
patterns = [ 'cat', 'dog' ]

# Text to parse
text = 'This is a string with the word cat, but no other words'

for pattern in patterns:
  print(f'Searching for pattern "{pattern}" in: \n"{text}"')

# Check for match
if re.search(pattern, text):
  print('Match was found. \n')
else:
  print('No Match was found.\n')

Searching for pattern "cat" in: 
"This is a string with the word cat, but no other words"
Searching for pattern "dog" in: 
"This is a string with the word cat, but no other words"
No Match was found.



Now we have seen that `re.search()` will take a pattern, scan the text, and then return a **Match** object. If no pattern is found, **None** is returned. To give you a clearer picture of this match object, look at the cell below:

In [4]:
# List of patterns to search for
pattern = 'cat'

# Text to parse
text = 'This is a string with the word cat, but no other words'

match = re.search(pattern, text)

type(match)

re.Match

The **Match** object returned by the `search()` method is more than just a **Boolean** or **None**, it contains information about the match, including the original input string, the regex used, and the location of the match. Let's look at the methods we can use on the match object:

In [5]:
# Show start of match
match.start()

31

In [6]:
# Show start of match
match.end()

34

## **2. Split with regular expressions**

Let's see how we can split with the re syntax. This will look similar to how you would use the `split()` method on a string.

In [7]:
# Term to split on
split_term = '@'

phrase = 'What is the domain name of someone who uses the email: hello@gmail.com'

# Split the phrase
re.split(split_term,phrase)

['What is the domain name of someone who uses the email: hello', 'gmail.com']

Note how `re.split()` returns the list in a split string version.

## **3. Substitutes with regular expressions**

Another very useful regex function is `re.sub()`, which replaces one bit of text with another if it finds a match. Here is an example:

In [8]:
sentence = '''The analytics firm uses a range of BI tools to visualize data. Their internal data science team suggests
bi tools may be their most valuable resource.'''

match = re.sub(r'bi','business intelligence', sentence, flags=re.IGNORECASE)
# The IGNORECASE flag allows for matches regardless of the case

print(match)

The analytics firm uses a range of business intelligence tools to visualize data. Their internal data science team suggests
business intelligence tools may be their most valuable resource.


## **4. Finding all instances of a pattern**

We can use `re.findall()` to find all instances of a pattern in a string. For example:

In [9]:
# Returns a list of all matches
# syntax : re.findall(pattern, string)

re.findall('cat','There is a cat here, there is a cat there, everywhere there is a cat. Even my email is cat123@gmail.com')

['cat', 'cat', 'cat', 'cat']

## **5. Character Set**

Character set is used when you want to match one of a group of characters at a point in the input. Parentheses are used to create a character set input. For example: input [ab] searches for occurrences of a or b. In general, the rules for character sets are as follows:

- using square brackets []
- [] indicates the desired character
- [] represents a slot for a single character

Let's look at some examples:

- search/find the word `cough`

In [10]:
words = 'Orang Batak botak kepala batok pakai batik batuk-batuk.'
pattern =  'batuk'

re.findall(pattern = pattern, string = words)
# output is [ 'batuk',  'batuk']
#  'batuk' from  'batuk'
#  'batuk' from  'batuk'

['batuk', 'batuk']

- search/find the words `batik` and `batuk`

In [11]:
words = 'Orang Batak botak kepala batok pakai batik batuk-batuk.'
pattern = 'bat[iu]k'

re.findall(pattern = pattern, string = words)
# only match with words whose 3rd index is the letter 'i' or 'u'

['batik', 'batuk', 'batuk']

- search for/find the words `Batak, batok, batik` and `batuk`

In [12]:
words = 'Orang Batak botak kepala batok pakai batik batuk-batuk.'
pattern = '[Bb]at[aiuo]k'

re.findall(pattern = pattern, string = words)
# only match with words whose 3rd index is the letter 'a', 'i', 'u' or 'o'

['Batak', 'batok', 'batik', 'batuk', 'batuk']

## **6. Character Range**

As character sets grow larger, typing out every character that should (or shouldn't) match can become tedious. A more concise format using character ranges allows you to specify the character set to include all adjacent characters between a start point and an end point. The format used is `[start-end]`.

A common use case is to search for a specific range of letters in the alphabet, such as `[a-f]` will match any letter between a and f.

Let's look at a few examples:

- search for words with 5 letters, starting with 'de', then followed by any 3 lower case letters.

In [13]:
words = 'debam, de.um, deCAK, dengung, denTum, denting, der1k, derIt, dering, des4H, desing, des!r, deSI5, det@k'

pattern = 'de[abcdefghijklmnopqrstuvwxyz][abcdefghijklmnopqrstuvwxyz][abcdefghijklmnopqrstuvwxyz]'  # character set : mentions one by one the letters from a to z

re.findall(pattern = pattern, string = words)

['debam', 'dengu', 'denti', 'derin', 'desin']

In [14]:
words = 'debam, de.um, deCAK, dengung, denTum, denting, der1k, derIt, dering, des4H, desing, des!r, deSI5, det@k'
pattern = 'de[a-z][a-z][a-z]'  # character range : specifies the range of letters

re.findall(pattern = pattern, string = words)

['debam', 'dengu', 'denti', 'derin', 'desin']

- search for words with 5 letters, starting with 'de', then followed by 3 lowercase or uppercase letters.

In [15]:
words = 'debam, de.um, deCAK, dengung, denTum, denting, der1k, derIt, dering, des4H, desing, des!r, deSI5, det@k'
pattern = 'de[a-zA-Z][a-zA-Z][a-zA-Z]'

re.findall(pattern = pattern, string = words)

['debam', 'deCAK', 'dengu', 'denTu', 'denti', 'derIt', 'derin', 'desin']

- search for words with 5 letters, starting with 'de', then followed by 3 lowercase letters, uppercase letters, or any number.

In [16]:
words = 'debam, de.um, deCAK, dengung, denTum, denting, der1k, derIt, dering, des4H, desing, des!r, deSI5, det@k'
pattern = 'de[a-zA-Z0-9!-_][a-zA-Z0-9!-_][a-zA-Z0-9!-_]'

re.findall(pattern = pattern, string = words)

['debam',
 'de.um',
 'deCAK',
 'dengu',
 'denTu',
 'denti',
 'der1k',
 'derIt',
 'derin',
 'des4H',
 'desin',
 'des!r',
 'deSI5',
 'det@k']

In [17]:
words = 'debam, de.um, deCAK, dengung, denTum, denting, der1k, derIt, dering, des4H, desing, des!r, deSI5, det@k'
pattern = 'de...'                    # . is a wildcard consisting of any character

re.findall(pattern = pattern, string = words)

['debam',
 'de.um',
 'deCAK',
 'dengu',
 'denTu',
 'denti',
 'der1k',
 'derIt',
 'derin',
 'des4H',
 'desin',
 'des!r',
 'deSI5',
 'det@k']

- search for words with `de.um`.

In [18]:
words = 'debam, de.um, deCAK, dengung, denTum, denting, der1k, derIt, dering, des4H, desing, des!r, deSI5, det@k'
pattern = 'de[.]um'

re.findall(pattern = pattern, string = words)

['de.um']

In [19]:
words = 'debam, de.um, deCAK, dengung, denTum, denting, der1k, derIt, dering, des4H, desing, des!r, deSI5, det@k'
pattern = 'de\.um'         # backslash acts as an escape character so that the dot is read as a dot

re.findall(pattern = pattern, string = words)

['de.um']

- create a pattern that matches `XRA 000`, `1AA 2CD`, and `XYZ 481`

In [20]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '[A-Z0-9][A-Z][A-Z] [0-9][A-Z0-9][A-Z0-9]'

re.findall(pattern = pattern, string = words)
# xyz 481 --> does not match because 'xyz' is lowercase
# XYZ 481 --> matches, because it matches the pattern for the first 7 characters

['XRA 000', '1AA 2CD', 'XYZ 481']

## **7. Quantified Repetition**

Sometimes we want to determine the number of repetitions we want without having to rewrite the desired characters many times. We can use the syntax `{minimum_characters, maximum_characters}` where `minimum_characters` is mandatory. The syntax will be attached to the character before the `{}` sign.

- create a pattern that matches `XRA 000, 1AA 2CD`, and `XYZ 481`

In [21]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '[A-Z0-9][A-Z]{2} [0-9][A-Z0-9]{2}'

re.findall(pattern = pattern, string = words)

# pattern '[A-Z0-9][A-Z]{2} [0-9][A-Z0-9]{2}' is equivalent to
# pattern '[A-Z0-9][A-Z][A-Z] [0-9][A-Z0-9][A-Z0-9]'

['XRA 000', '1AA 2CD', 'XYZ 481']

- create a pattern that matches `XYZ 4810`

In [22]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '[A-Z0-9][A-Z]{2} [0-9][A-Z0-9]{3}'

re.findall(pattern = pattern, string = words)

['XYZ 4810']

- create a pattern that matches `XRA 000, 1AA 2CD` and `XYZ 4810`

In [23]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '[A-Z0-9][A-Z]{2} [0-9][A-Z0-9]{2,3}'

re.findall(pattern = pattern, string = words)
# repetition only applies to characters attached with curly brackets
# [A-Z]{2} --> means capital letters are repeated 2 times
# [A-Z0-9]{2,3} --> means capital letters or numbers are repeated at least 2 times and a maximum of 3 times

['XRA 000', '1AA 2CD', 'XYZ 4810']

- create a pattern that matches `XRA 000, 1AA 2CD, XYZ 4810`, and `ABC 77`

In [24]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '[A-Z0-9][A-Z]{2} [0-9][A-Z0-9]{1,3}'

re.findall(pattern = pattern, string = words)

# pattern '[A-Z0-9][A-Z]{2} [0-9][A-Z0-9]{1,3}' is equivalent to:
# '[A-Z0-9][A-Z][A-Z] [0-9][A-Z0-9]'
# '[A-Z0-9][A-Z][A-Z] [0-9][A-Z0-9][A-Z0-9]'
# '[A-Z0-9][A-Z][A-Z] [0-9][A-Z0-9][A-Z0-9][A-Z0-9]'

['XRA 000', '1AA 2CD', 'XYZ 4810', 'ABC 77']

## **8. Metacharacters**

We can use special escape codes to find certain types of patterns in your data, such as digits, non-digits, spaces, and more. For example:

Code | Meaning
--- | ---
\d | a digit [0-9]
\D | a non-digit
\w | alphanumeric [a-zA-Z0-9_]
\W | non-alphanumeric
\s | whitespace (tab, space, newline, etc.)
\S | non-whitespace

- create a pattern that matches `XRA 000, 1AA 2CD, XYZ 4810`, and `ABC 77`

In [25]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '[A-Z0-9][A-Z]{2} [0-9][A-Z0-9]{1,3}'

re.findall(pattern = pattern, string = words)

['XRA 000', '1AA 2CD', 'XYZ 4810', 'ABC 77']

In [26]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '\w[A-Z]{2}\s\d\w{1,3}'

re.findall(pattern = pattern, string = words)

['XRA 000', '1AA 2CD', 'XYZ 4810', 'ABC 77']

- create a pattern that matches `XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000`, and `ABC 77`

In [27]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '\w{3}\s\d\w{1,3}'

re.findall(pattern = pattern, string = words)

# xyz 4810 --> join the match, because \w represents alphanumeric (uppercase, lowercase, numbers, and also underscore)

['XRA 000', '1AA 2CD', 'xyz 4810', 'XYZ 4810', 'XR1 000', 'ABC 77']

## **9. Exclusion**

We can use ^ to exclude terms by enclosing them in bracket syntax notation. For example: `[^...]` will match any character not in the brackets. Let's look at an example:

- create a pattern that matches `XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, ABC 77`, and `XY@ 123`

In [28]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '\w{2}[^\d]\s\d\w{1,3}'

re.findall(pattern = pattern, string = words)

['XRA 000', '1AA 2CD', 'xyz 4810', 'XYZ 4810', 'ABC 77', 'XY@ 123']

## **10. Repetition Metacharacters**

In addition to the metacharacters mentioned above, there are repetition metacharacters that request more than one occurrence of a character. The following table shows all repetition metacharacters.

| Quantifier | Role |
| --- | --- |
| \* | 0 or more. Same as { , } |
| \+ | 1 or more. Same as {1, } |
| \? | Optional, so 0 or 1. Same as { ,1}. |

- `\*` matches 0 or more repetitions

In [29]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '\w*\s\d*'

re.findall(pattern = pattern, string = words)

# \w* --> lowercase or uppercase or number or underscore repeated 0 times or more
# \s --> space
# \d* --> number repeated 0 times or more

['XRA 000',
 ' 1',
 'AA 2',
 ' ',
 'xyz 4810',
 ' ',
 'XYZ 4810',
 ' ',
 'XR1 000',
 ' ',
 'ABC 77',
 ' ',
 'COD 1',
 ' ',
 ' 123']

- `\+` matches 1 or more repetitions

In [30]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '\w+\s\d+'

re.findall(pattern = pattern, string = words)

# \w+ --> lowercase or uppercase letters or numbers or underscores repeated 1 time or more
# \s --> space
# \d+ --> numbers repeated 1 time or more

# means there is a space on the left of which is a letter or number or underscore is a number at least 1 time
# and on the right is a number at least 1 time or more

['XRA 000', '1AA 2', 'xyz 4810', 'XYZ 4810', 'XR1 000', 'ABC 77', 'COD 1']

- `\?` matches 0 or 1 repetitions

In [31]:
words = 'XRA 000, 1AA 2CD, xyz 4810, XYZ 4810, XR1 000, ABC 77, COD 1, XY@ 123'
pattern = '\w?\s\d?'

re.findall(pattern = pattern, string = words)

['A 0',
 ' 1',
 'A 2',
 ' ',
 'z 4',
 ' ',
 'Z 4',
 ' ',
 '1 0',
 ' ',
 'C 7',
 ' ',
 'D 1',
 ' ',
 ' 1']

- displays the letters of each account

In [32]:
words = 'rihanna, ChampionsLeague, BTS_twt, taylorswift13, NICKIMINAJ, KevinHart4real, 10Ronaldinho'
pattern = '[A-Za-z]+'

re.findall(pattern = pattern, string = words)

['rihanna',
 'ChampionsLeague',
 'BTS',
 'twt',
 'taylorswift',
 'NICKIMINAJ',
 'KevinHart',
 'real',
 'Ronaldinho']

- displays the numbers of each account

In [33]:
words = 'rihanna, ChampionsLeague, BTS_twt, taylorswift13, NICKIMINAJ, KevinHart4real, 10Ronaldinho'
pattern = '\d+'

re.findall(pattern = pattern, string = words)

['13', '4', '10']

- displays each account

In [34]:
words = 'rihanna, ChampionsLeague, BTS_twt, taylorswift13, NICKIMINAJ, KevinHart4real, 10Ronaldinho'
pattern = '\w+'

re.findall(pattern = pattern, string = words)

['rihanna',
 'ChampionsLeague',
 'BTS_twt',
 'taylorswift13',
 'NICKIMINAJ',
 'KevinHart4real',
 '10Ronaldinho']

- displays the numbers of each account

In [35]:
words = 'rihanna, ChampionsLeague, BTS_twt, taylorswift13, NICKIMINAJ, KevinHart4real, 10Ronaldinho'
pattern = '\w*\d+\w*'

re.findall(pattern = pattern, string = words)

# '[^\s,]+' --> characters other than spaces and commas repeated at least 1 time or more

['taylorswift13', 'KevinHart4real', '10Ronaldinho']

## **11. Grouping**

We can use grouping to search for characters that are exactly the same as the regex that is in the brackets `()`. The benefits of grouping include being able to apply loops to groups and making the regex easier to read.

In [36]:
words = 'ab, abc, abcc, abcccc, abcabc, abcabcabc'
pattern = 'abc+'

re.findall(pattern = pattern, string = words)

['abc', 'abcc', 'abcccc', 'abc', 'abc', 'abc', 'abc', 'abc']

In the example above, the repetition metacharacter '+' is attached to the character `c`, so that `c` is at least 1 time or more.

In [37]:
words = 'ab, abc, abcc, abcccc, abcabc, abcabcabc'
pattern = '(abc)+'

re.findall(pattern = pattern, string = words)

['abc', 'abc', 'abc', 'abc', 'abc']

In the example above, the repetition metacharacter '+' is attached to the character `abc`, so that `abc` is at least 1 time or more.
The subtring displayed is the pattern in parentheses.

In [38]:
words = 'ab, abc, abcc, abcccc, abcabc, abcabcabc'
pattern = '(?:abc)+'

re.findall(pattern = pattern, string = words)

['abc', 'abc', 'abc', 'abcabc', 'abcabcabc']

By using the `?:` sign in the grouping, all substrings that contain `abc` 1 or more times are displayed: `abc`, `abcabc`, etc.

## **12. Alternative**

We can use the `|` sign as an alternative. Its function is similar to OR in python.

- create a pattern that displays `pineapple juice` and `watermelon juice` without grouping.

In [39]:
words = 'apple juice, melon juice, watermelon juice, apple pie, pineapple juice'
pattern = 'pineapple juice|watermelon juice'

re.findall(pattern = pattern, string = words)

['watermelon juice', 'pineapple juice']

- create a pattern that displays `pineapple juice` and `watermelon juice` with grouping.

In [40]:
words = 'apple juice, melon juice, watermelon juice, apple pie, pineapple juice'
pattern = '(pineapple|watermelon) juice'

re.findall(pattern = pattern, string = words)
# here match with pineapple juice and watermelon juice
# but only the ones in brackets ('pineapple' and 'watermelon') are displayed

['watermelon', 'pineapple']

In [41]:
words = 'apple juice, melon juice, watermelon juice, apple pie, pineapple juice'
pattern = '(?:pineapple|watermelon) juice'

re.findall(pattern = pattern, string = words)
# here match with pineapple juice and watermelon juice
# and what is displayed is according to pineapple juice and watermelon juice

['watermelon juice', 'pineapple juice']

## **13. Word Boundaries**

By using `\b` at the beginning and end of the pattern, we ensure that the match starts and ends as a whole word, not part of another word.

- create a pattern to display `red` from the words **red, hundred, and reddit**

In [42]:
words = 'red, hundred, reddit'
pattern = 'red'

re.findall(pattern = pattern, string = words)

['red', 'red', 'red']

- create a pattern to display `red` from the words **red and reddit**

In [43]:
# display 'red' from 'red' and 'reddit'
words = 'red, hundred, reddit'
pattern = '\\bred'

re.findall(pattern = pattern, string = words)

# output : ['red', 'red'] --> first red from red and second red from reddit
# red in hundred is not included, because before red there is a character

['red', 'red']

Notes: we have to use the additional escape character '\' so that Python doesn't mistake `\b` as backspace.

- create a pattern to display `red` from the words **red and hundred**

In [44]:
words = 'red, hundred, reddit'
pattern = 'red\\b'

re.findall(pattern = pattern, string = words)

# output : ['red', 'red'] --> first red from red and second red from hundred
# red in reddit is not included, because after red there is a character

['red', 'red']

- create a pattern to display `red` from the word **red**

In [45]:
words = 'red, hundred, reddit'
pattern = '\\bred\\b'

re.findall(pattern = pattern, string = words)

# output : ['red'] --> red from red
# red in hundred is not included, because before red there is a character
# red in reddit is not included, because after red there is a character

['red']

- create a pattern that displays words consisting of only 5 characters.

In [46]:
words = 'debam, debum, decak, dengung, dentum, denting, derik, derit, dering, desah, desing, desir, desis, detak'
pattern = '\\b\w{5}\\b'

re.findall(pattern = pattern, string = words)

['debam',
 'debum',
 'decak',
 'derik',
 'derit',
 'desah',
 'desir',
 'desis',
 'detak']

- create a pattern that displays `apple juice` and `melon juice`

In [47]:
words = 'apple juice, melon juice, watermelon juice, apple pie, pineapple juice'
pattern = '(?:\\bapple|\\bmelon) juice'

re.findall(pattern = pattern, string = words)

['apple juice', 'melon juice']

- create a pattern that displays `ooops` and `oooooops`

In [48]:
words = 'ops oops ooops oooops ooooops oooooops ooooooops'
pattern = '\\b(?:ooo)+ps'

re.findall(pattern = pattern, string = words)

['ooops', 'oooooops']

## **14. Raw Strings**

We can use `r` before the quotes so that all characters in the string are read as text.

In [49]:
print('This is hello world')

This is hello world


In [50]:
print('This is hello\b world')

This is hello world


In python `\b` means backspace or delete 1 character. Now we will try to add raw string.

In [51]:
print(r'This is hello\b world')

This is hello\b world


After adding the raw string, `\b` becomes `\b` itself.

- create a pattern that displays `ooops` and `oooooops`

In [52]:
# create a pattern that displays ooops and oooooops
words = 'ops oops ooops oooops ooooops oooooops ooooooops'
pattern = '\b(?:ooo)+ps'

re.findall(pattern = pattern, string = words)
# none matches because \b is read as backspace

[]

In [53]:
# create a pattern that displays ooops and oooooops
words = 'ops oops ooops oooops ooooops oooooops ooooooops'
pattern = r'\b(?:ooo)+ps'

re.findall(pattern = pattern, string = words)
# after adding rawstring, \b is read as word boundary in regex

['ooops', 'oooooops']